[package]
name = "agical-tutorial"
version = "0.1.6"
edition = "2021"

[dependencies]
macroquad = "0.4"

[package.metadata.android]
build_targets = ["aarch64-linux-android"]

[package.metadata.android.activity_attributes]
"android:exported" =  "true"